encoding: bom|utf-8

title: Продажа авто в Самаре, автоцентры и автосалоны Самары по продаже новых
name: Самарские автомобили
description: Группа компаний «Самарские автомобили» предлагает новые авто в Самаре! Продажа новых автомобилей осуществляется на правах официального дилера в автосалонах Самары.
keywords: ""
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

aside_menu:
  - title: "Главная"
    url: "/"
  - title: "Автоцентры"
    url: "#"
    submenu:
      - title: "на Южном шоссе"
        url: "/centers/south/"
      - title: "на Авроре"
        url: "/centers/aurora/"
  - title: "Кредит и лизинг"
    url: "/credit/"
  - title: "Автомобили с пробегом"
    url: "https://probegcentr.ru/"
    target: true
  - title: "О компании"
    url: "/about/"
  - title: "Кузовной ремонт"
    url: "/carrepair/"
  - title: "Авто Уход"
    url: "/carcare/"
  - title: "Акции сервиса"
    url: "/spo_serv/"
  - title: "Спецпредложения"
    url: "/specials/"

cars_menu:
  - title: "Москвич"
    url: "/cars/moskvich/"
    logo: "img/brands/moskvich.jpg"
  - title: "Infiniti"
    url: "/cars/infiniti/"
    logo: "img/brands/infiniti.jpg"
  - title: "Jaguar"
    url: "/cars/jaguar/"
    logo: "img/brands/jaguar.jpg"
  - title: "Land Rover"
    url: "/cars/landrover/"
    logo: "img/brands/land-rover.jpg"
  - title: "Nissan"
    url: "/cars/nissan/"
    logo: "img/brands/nissan.jpg"

exclude:
  - README.md
  - mix-manifest.json
  - package.json
  - src
  - webpack.mix.js
  - yarn.lock
  - docker-compose.yml
  - package-lock.json
  - tailwind.config.js